services:
  db:
    image: postgres:17.0-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - d4d-v2-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: d4d-backend-v2
    depends_on:
      - db
    restart: on-failure
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/db
      QUARKUS_DATASOURCE_USERNAME: app
      QUARKUS_DATASOURCE_PASSWORD: app
      QUARKUS_PROFILE: dev
      # Gmail SMTP Configuration
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USERNAME: d4d.notification@gmail.com
      SMTP_PASSWORD: ehzrxtbcdbdngxys
      SMTP_FROM: d4d.notification@gmail.com
      TEST_EMAIL: s.jelic@htl-leonding.ac.at
    networks:
      - d4d-v2-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: d4d-frontend-v2
    depends_on:
      - backend
    networks:
      - d4d-v2-net

  nginx:
    image: nginx:latest
    container_name: nginx-reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx-dev.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - frontend
      - backend
    networks:
      - d4d-v2-net

  init-testdata:
    image: curlimages/curl
    container_name: init-testdata
    depends_on:
      - backend
    entrypoint: >
      sh -c "
      echo 'Warte auf Backend...' &&
      until curl -s http://backend:8080/q/health; do sleep 1; done &&
      echo 'Backend erreichbar' &&
      curl -X POST http://backend:8080/d4d/testdata/generate-service-types &&
      curl -X POST http://backend:8080/d4d/testdata/generate-users &&
      curl -X POST http://backend:8080/d4d/testdata/generate-markets &&
      curl -X POST http://backend:8080/d4d/testdata/generate-services &&
      curl -X POST http://backend:8080/d4d/testdata/generate-chat-entries &&
      curl -X POST http://backend:8080/d4d/testdata/generate-reviews &&
      echo 'Testdaten erfolgreich eingef√ºgt.'"
    restart: "no"
    networks:
      - d4d-v2-net

networks:
  d4d-v2-net:
    driver: bridge

volumes:
  pgdata:
